/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.dbConnector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author milan
 */
public class Loads extends javax.swing.JFrame {

    /**
     * Creates new form ViewAssignedLoads
     */
    public Loads() {
        initComponents();
        
        
     }
      
    
    public void loadLoadsData() {
    DefaultTableModel model = (DefaultTableModel) loadtbl.getModel();
    model.setRowCount(0);  // Clear the table before reloading data

    String sql = "SELECT load_id, cargo, destination, weight, Status FROM tbl_loads";
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sarns", "root", "");
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("load_id"),          // Load ID
                rs.getString("cargo"),         // Cargo
                rs.getString("destination"),   // Destination
                rs.getInt("weight"),           // Weight
                rs.getString("Status")    // Status (e.g., Delivered)
            });
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error loading load data: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}

            
         
private void loadAssignedLoads() {
    dbConnector connector = new dbConnector();
    try (Connection con = connector.getConnection()) {

        // Update 'Pending' load status to 'Active' for recent loads
        String updateQuery = "UPDATE tbl_loads SET status = 'Active' WHERE status = 'Pending'";
        try (PreparedStatement updateStmt = con.prepareStatement(updateQuery)) {
            updateStmt.executeUpdate();
        }

        // Fetch updated loads including load details
        String selectQuery = "SELECT l.load_id, l.cargo, l.destination, l.weight, l.status " +
                             "FROM tbl_loads l " +
                             "ORDER BY l.load_id DESC";

        try (Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(selectQuery)) {

            // Update column names to match the "load" data columns
            DefaultTableModel model = new DefaultTableModel(
                new String[]{"Load ID", "Cargo", "Destination", "Weight", "Status"}, 0 // Updated to "Load ID", "Cargo", "Destination", "Weight", "Status"
            );

            while (rs.next()) {
                // Populate the table with the appropriate load data
                model.addRow(new Object[]{
                    rs.getInt("load_id"),        // Load ID
                    rs.getString("cargo"),       // Cargo
                    rs.getString("destination"), // Destination
                    rs.getInt("weight"),         // Weight
                    rs.getString("status")  // Status
                });
            }

            loadtbl.setModel(model); // Set model to loadtbl

        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error loading loads: " + ex.getMessage());
    }
}

            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        select = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loadtbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, 30));

        select.setBackground(new java.awt.Color(0, 0, 204));
        select.setText("Select");
        select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectMouseClicked(evt);
            }
        });
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel2.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 80, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("LOADS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 90, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 204));
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 70, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        loadtbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        loadtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Load ID", "Cargo", "Destination", "Weight", "Status"
            }
        ));
        jScrollPane1.setViewportView(loadtbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 770, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         loadAssignedLoads();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
  int rowIndex = loadtbl.getSelectedRow();

// Check if a row is selected
if (rowIndex == -1) {
    JOptionPane.showMessageDialog(this, "Please select a load to proceed.");
    return; // Exit if no row is selected
}

// Retrieve the status of the selected row
String status = loadtbl.getModel().getValueAt(rowIndex, 4).toString(); // Assuming column index 4 is 'Status'

// Check if the status is "Delivered"
if ("Delivered".equalsIgnoreCase(status)) {
    JOptionPane.showMessageDialog(this, "You cannot select a delivered load. Please select an active load.");
    return; // Exit if load is delivered
}

// Retrieve the load details from the selected row
String loadId = loadtbl.getModel().getValueAt(rowIndex, 0).toString();
String cargo = loadtbl.getModel().getValueAt(rowIndex, 1).toString();
String destination = loadtbl.getModel().getValueAt(rowIndex, 2).toString();
String weight = loadtbl.getModel().getValueAt(rowIndex, 3).toString();

// Create the LoadTransaction form
LoadTransaction loadTransaction = new LoadTransaction();

// Pass the load details to the LoadTransaction form
loadTransaction.setLoadDetails(loadId, cargo, destination, weight); 

// Make LoadTransaction visible and dispose of the current window
loadTransaction.setVisible(true);
this.dispose();

            
    }//GEN-LAST:event_selectActionPerformed

    private void selectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectMouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_selectMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  loadLoadsData();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        userDashboard userDashboard = new userDashboard();
        userDashboard.setVisible(true); // Show the AdminDashboard
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loads().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable loadtbl;
    private javax.swing.JButton select;
    // End of variables declaration//GEN-END:variables
}
